import pyautogui
import time
pyautogui.FAILSAFE = False

while True:
    time.sleep(5)
    for i in range(0, 100):
        pyautogui.moveTo(i*10, i*5)
    for i in range(0,3):
        time.sleep(1)
        pyautogui.click(0,0)
        pyautogui.press('shift')
        time.sleep(1)
        pyautogui.click(0,0)
        pyautogui.press('ctrl')
        time.sleep(1)
        pyautogui.click(0,0)
        pyautogui.press('shift')
        time.sleep(1)
        pyautogui.keyDown('alt')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.keyUp('alt')
        time.sleep(1)
        pyautogui.keyDown('ctrl')
        time.sleep(1)
        pyautogui.press('tab')
        pyautogui.press('tab')
        pyautogui.keyUp('ctrl')
        pyautogui.press('up')
        pyautogui.press('up')
        pyautogui.press('up')
        pyautogui.press('up')
        time.sleep(1)
        pyautogui.press('up')
        time.sleep(1)
        pyautogui.press('up')
        pyautogui.press('down')
        pyautogui.press('down')
        pyautogui.press('up')
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('up')
        time.sleep(1)
        pyautogui.press('down')
        pyautogui.press('left')
        time.sleep(1)
        pyautogui.press('left')
        pyautogui.press('left')
        time.sleep(1)
        pyautogui.press('left')
        time.sleep(1)
        time.sleep(1)
        pyautogui.press('up')
        time.sleep(1)
        pyautogui.press('right')
        time.sleep(1)
        pyautogui.press('right')
        time.sleep(1)
        pyautogui.press('right')
        time.sleep(1)
        pyautogui.press('right')
        time.sleep(1)
        time.sleep(1)
        pyautogui.press('up')
